/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPages;

import components.CustomTable;
import components.SideMenu;
import db.DBConnection;
import insertPages.ExtendContractPage;
import insertPages.FinalizeContractPage;
import java.awt.BorderLayout;
import java.sql.*;

/**
 *
 * @author Administrator
 */
public class ContractsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContractsPage.class.getName());
    private final CustomTable tabelaKomponenta;
    /**
     * Creates new form Contracts
     */
    public ContractsPage() {
        initComponents();
        this.setSize(1093, 571);
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        SideMenu menu = new SideMenu("Ugovori");

        finalizujBtn.setEnabled(false);
        produziBtn.setEnabled(false);
        
        SideP.setLayout(new BorderLayout());
        SideP.add(menu, BorderLayout.CENTER);
        // Inicijalizacija tabele sa kolonama
        String[] kolone = {"Broj Ugovora", "Klijent", "Matični Broj", "Model", "Registracija", "Datum Sklapanja", "Planirani Povratak", "Troškovi", "Status"};
        tabelaKomponenta = new CustomTable(kolone);
        TableContainer.setLayout(new BorderLayout());
        TableContainer.add(tabelaKomponenta, BorderLayout.CENTER);

        // 3. Osvježavanje forme
        TableContainer.revalidate();
        TableContainer.repaint();
        tabelaKomponenta.getTable().getSelectionModel().addListSelectionListener(e -> {
         if (!e.getValueIsAdjusting()) {
             int row = tabelaKomponenta.getTable().getSelectedRow();
             if (row != -1) {
                 String status = tabelaKomponenta.getTable().getValueAt(row, 8).toString();
                 produziBtn.setEnabled(status.equals("Aktivan"));
                 finalizujBtn.setEnabled(status.equals("Aktivan"));
             }
         }
        });
      
        loadUgovori(tabelaKomponenta);
    }
    
    private void loadUgovori(CustomTable tableComp) {
        String sql = "SELECT u.BrojUgovora, k.Ime, k.Prezime, k.Maticni_Broj, a.Model, a.Registracija, " +
                     "u.DatumSklapanja, u.PlaniraniDatumVracanja, u.TroskoviNajma, u.Status " +
                     "FROM Ugovori u " +
                     "JOIN Klijenti k ON u.KlijentID = k.Id " +
                     "JOIN Automobili a ON u.AutomobilID = a.Id";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            tableComp.clearTable();
            while (rs.next()) {
                tableComp.addRow(new Object[]{
                    rs.getInt("BrojUgovora"),
                    rs.getString("Ime") + " " + rs.getString("Prezime"),
                    rs.getString("Maticni_Broj"),
                    rs.getString("Model"),
                    rs.getString("Registracija"),
                    rs.getDate("DatumSklapanja"),
                    rs.getDate("PlaniraniDatumVracanja"),
                    rs.getInt("TroskoviNajma") + " €",
                    rs.getString("Status")
                });
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Greška pri učitavanju ugovora", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        SideP = new javax.swing.JPanel();
        TableContainer = new javax.swing.JPanel();
        finalizujBtn = new javax.swing.JButton();
        produziBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RENT A CAR");

        javax.swing.GroupLayout SidePLayout = new javax.swing.GroupLayout(SideP);
        SideP.setLayout(SidePLayout);
        SidePLayout.setHorizontalGroup(
            SidePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );
        SidePLayout.setVerticalGroup(
            SidePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TableContainerLayout = new javax.swing.GroupLayout(TableContainer);
        TableContainer.setLayout(TableContainerLayout);
        TableContainerLayout.setHorizontalGroup(
            TableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        TableContainerLayout.setVerticalGroup(
            TableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        finalizujBtn.setText("Finalizuj");
        finalizujBtn.addActionListener(this::finalizujBtnActionPerformed);

        produziBtn.setText("Produzi");
        produziBtn.addActionListener(this::produziBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(SideP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(finalizujBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(produziBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SideP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizujBtn)
                    .addComponent(produziBtn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizujBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizujBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelaKomponenta.getTable().getSelectedRow();

        // 2. Sigurnosna provera
        if (selectedRow != -1) {
            // 3. Uzimanje ID-a iz prve kolone (Broj Ugovora)
            // Pretpostavljam da je Broj Ugovora u 0. koloni (prva kolona)
            int idUgovora = (int) tabelaKomponenta.getTable().getValueAt(selectedRow, 0);

            // 4. Otvaranje novog prozora i prosleđivanje ID-a
            FinalizeContractPage finalizePage = new FinalizeContractPage(idUgovora);
            finalizePage.setVisible(true);
            this.dispose();
            // 5. Opciono: Ako želiš da zatvoriš trenutni prozor kada otvoriš finalizaciju
            // this.dispose();
        } else {
            // Obaveštenje ako nešto nije dobro selektovano
            javax.swing.JOptionPane.showMessageDialog(this, "Molimo selektujte ugovor iz tabele.");
        }
    }//GEN-LAST:event_finalizujBtnActionPerformed

    private void produziBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produziBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelaKomponenta.getTable().getSelectedRow();

        // 2. Sigurnosna provera
        if (selectedRow != -1) {
            // 3. Uzimanje ID-a iz prve kolone (Broj Ugovora)
            // Pretpostavljam da je Broj Ugovora u 0. koloni (prva kolona)
            int idUgovora = (int) tabelaKomponenta.getTable().getValueAt(selectedRow, 0);

            // 4. Otvaranje novog prozora i prosleđivanje ID-a
            ExtendContractPage extendPage = new ExtendContractPage(idUgovora);
            extendPage.setVisible(true);
            this.dispose();
            // 5. Opciono: Ako želiš da zatvoriš trenutni prozor kada otvoriš finalizaciju
            // this.dispose();
        } else {
            // Obaveštenje ako nešto nije dobro selektovano
            javax.swing.JOptionPane.showMessageDialog(this, "Molimo selektujte ugovor iz tabele.");
        }
    }//GEN-LAST:event_produziBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContractsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SideP;
    private javax.swing.JPanel TableContainer;
    private javax.swing.JButton finalizujBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton produziBtn;
    // End of variables declaration//GEN-END:variables
}
