/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPages;
import components.SideMenu;
import db.DBConnection;
import insertPages.MakeAContract;
import java.awt.BorderLayout;
import session.Session;

/**
 *
 * @author Administrator
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import session.SelectedCar;
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form home
     */
    private void initCustomTableStyle() {
    // 1. Remove grid lines and collapse spacing
        automobili.setShowGrid(false);
        automobili.setIntercellSpacing(new java.awt.Dimension(0, 0));
        automobili.setRowHeight(35);
        automobili.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // 2. Style the Header (Teal background)
        javax.swing.table.JTableHeader header = automobili.getTableHeader();
        header.setBackground(new java.awt.Color(165, 225, 215)); // Teal header
        header.setForeground(java.awt.Color.BLACK);
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        header.setOpaque(true);
    }
    
    private void loadAutomobili() {

        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT * FROM automobili";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) automobili.getModel();
            model.setRowCount(0);

            while(rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("Id"),
                    rs.getString("Model"),
                    rs.getString("Kategorija"),
                    rs.getInt("Godiste"),
                    rs.getInt("CenaPoDanu"),
                    rs.getInt("Kilometraza"),
                    rs.getString("Boja"),
                    rs.getString("Registracija"),
                    rs.getString("Status") // Use the converted string here
                });
            }

            rs.close();
            ps.close();
            con.close();

        } catch(SQLException ex) {
        }
    }
    private void centerTableData() {
    // Create a renderer that centers content
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        // Apply this renderer to every column in the table
        for (int i = 0; i < automobili.getColumnCount(); i++) {
            automobili.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    public HomePage() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        SideMenu menu = new SideMenu("Pocetna");

        SideP.setLayout(new BorderLayout());
        SideP.add(menu, BorderLayout.CENTER);

        SideP.revalidate();
        SideP.repaint();

        initCustomTableStyle();
        centerTableData();
        loadAutomobili();
        
        btnIznajmi.setEnabled(false);
        Sluzbenik.setText(Session.ime + " " + Session.prezime);
        
        automobili.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {

                int row = automobili.getSelectedRow();

                if (row != -1) {

                    String status = automobili.getValueAt(row, 8).toString();

                    btnIznajmi.setEnabled(status.equals("Slobodan"));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ImeSluzbenika = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sluzbenik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        automobili = new javax.swing.JTable();
        SideP = new javax.swing.JPanel();
        btnIznajmi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RENT A CAR");

        jLabel2.setText("Sluzbenik:");

        ImeSluzbenika.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Sluzbenik.setText("jLabel5");

        automobili.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        automobili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Model", "Kategorija", "Godiste", "CenaPoDanu", "Kilometraza", "Boja", "Registracija", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(automobili);

        javax.swing.GroupLayout SidePLayout = new javax.swing.GroupLayout(SideP);
        SideP.setLayout(SidePLayout);
        SidePLayout.setHorizontalGroup(
            SidePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SidePLayout.setVerticalGroup(
            SidePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        btnIznajmi.setText("Iznajmi");
        btnIznajmi.addActionListener(this::btnIznajmiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SideP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnIznajmi, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImeSluzbenika, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sluzbenik, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImeSluzbenika)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Sluzbenik)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SideP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIznajmi)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIznajmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIznajmiActionPerformed
        // TODO add your handling code here:
        int row = automobili.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Izaberite automobil.");
            return;
        }

        // Indeksi su sada: Id(0), Model(1), Kategorija(2), Godiste(3), Cena(4), Km(5), Boja(6), Reg(7), Status(8)
        SelectedCar.Id = Integer.parseInt(automobili.getValueAt(row, 0).toString());
        SelectedCar.Model = automobili.getValueAt(row, 1).toString();
        SelectedCar.Kategorija = automobili.getValueAt(row, 2).toString();
        SelectedCar.Godiste = Integer.parseInt(automobili.getValueAt(row, 3).toString());
        SelectedCar.CenaPoDanu = Integer.parseInt(automobili.getValueAt(row, 4).toString());
        SelectedCar.Kilometraza = Integer.parseInt(automobili.getValueAt(row, 5).toString());
        SelectedCar.Boja = automobili.getValueAt(row, 6).toString();
        SelectedCar.Registracija = automobili.getValueAt(row, 7).toString();
        
        JOptionPane.showMessageDialog(this, 
            "Iznajmljuje se automobil: " + SelectedCar.Model + " (" + SelectedCar.Registracija + ")", 
            "Potvrda izbora", 
            JOptionPane.INFORMATION_MESSAGE);

        MakeAContract contract = new MakeAContract();
        contract.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIznajmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImeSluzbenika;
    private javax.swing.JPanel SideP;
    private javax.swing.JLabel Sluzbenik;
    private javax.swing.JTable automobili;
    private javax.swing.JButton btnIznajmi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
