/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import mainPages.HomePage;
import mainPages.CarsPage;
import mainPages.ClientsPage;
import mainPages.ContractsPage;
import mainPages.ReceiptsPage;

/**
 *
 * @author Administrator
 */
public class SideMenu extends javax.swing.JPanel {

    /**
     * Creates new form SideMenu
     * @param activePage
     */
    public SideMenu(String activePage) {
        initComponents();
        highlightActive(activePage);
    }

    private void highlightActive(String activePage) {
        // Definiši moderniju boju (svetlo zelena)
        java.awt.Color activeColor = new java.awt.Color(144, 238, 144); 
        java.awt.Color defaultColor = java.awt.Color.BLACK;

        // Resetuj sve na crnu
        Pocetna.setBackground(defaultColor);
        Automobili.setBackground(defaultColor);
        Klijenti.setBackground(defaultColor);
        Ugovori.setBackground(defaultColor);
        Racuni.setBackground(defaultColor);

        // Postavi svetlo zelenu boju na aktivnu
        switch (activePage) {
            case "Pocetna"   -> Pocetna.setBackground(activeColor);
            case "Automobili" -> Automobili.setBackground(activeColor);
            case "Klijenti"   -> Klijenti.setBackground(activeColor);
            case "Ugovori"    -> Ugovori.setBackground(activeColor);
            case "Racuni"    -> Racuni.setBackground(activeColor);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void navigateTo(javax.swing.JFrame targetFrame) {
        targetFrame.setVisible(true);
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win != null) win.dispose();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideMenu = new javax.swing.JPanel();
        Pocetna = new javax.swing.JLabel();
        Automobili = new javax.swing.JLabel();
        Klijenti = new javax.swing.JLabel();
        Ugovori = new javax.swing.JLabel();
        Racuni = new javax.swing.JLabel();

        SideMenu.setBackground(new java.awt.Color(0, 153, 255));

        Pocetna.setBackground(new java.awt.Color(0, 0, 0));
        Pocetna.setForeground(new java.awt.Color(255, 255, 255));
        Pocetna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pocetna.setText("Pocetna");
        Pocetna.setOpaque(true);
        Pocetna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PocetnaMouseClicked(evt);
            }
        });

        Automobili.setBackground(new java.awt.Color(0, 0, 0));
        Automobili.setForeground(new java.awt.Color(255, 255, 255));
        Automobili.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Automobili.setText("Automobili");
        Automobili.setOpaque(true);
        Automobili.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutomobiliMouseClicked(evt);
            }
        });

        Klijenti.setBackground(new java.awt.Color(0, 0, 0));
        Klijenti.setForeground(new java.awt.Color(255, 255, 255));
        Klijenti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Klijenti.setText("Klijenti");
        Klijenti.setOpaque(true);
        Klijenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlijentiMouseClicked(evt);
            }
        });

        Ugovori.setBackground(new java.awt.Color(0, 0, 0));
        Ugovori.setForeground(new java.awt.Color(255, 255, 255));
        Ugovori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ugovori.setText("Ugovori");
        Ugovori.setOpaque(true);
        Ugovori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UgovoriMouseClicked(evt);
            }
        });

        Racuni.setBackground(new java.awt.Color(0, 0, 0));
        Racuni.setForeground(new java.awt.Color(255, 255, 255));
        Racuni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Racuni.setText("Racuni");
        Racuni.setOpaque(true);
        Racuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RacuniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SideMenuLayout = new javax.swing.GroupLayout(SideMenu);
        SideMenu.setLayout(SideMenuLayout);
        SideMenuLayout.setHorizontalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Racuni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pocetna, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(Automobili, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(Ugovori, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(Klijenti, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        SideMenuLayout.setVerticalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Pocetna, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Automobili, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Klijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ugovori, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Racuni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PocetnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PocetnaMouseClicked
       navigateTo(new HomePage());
    }//GEN-LAST:event_PocetnaMouseClicked

    private void AutomobiliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutomobiliMouseClicked
       navigateTo(new CarsPage());
    }//GEN-LAST:event_AutomobiliMouseClicked

    private void KlijentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlijentiMouseClicked
        // TODO add your handling code here:
       navigateTo(new ClientsPage());
    }//GEN-LAST:event_KlijentiMouseClicked

    private void UgovoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UgovoriMouseClicked
        // TODO add your handling code here:
       navigateTo(new ContractsPage());
    }//GEN-LAST:event_UgovoriMouseClicked

    private void RacuniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RacuniMouseClicked

       // TODO add your handling code here:
       navigateTo(new ReceiptsPage());        
    }//GEN-LAST:event_RacuniMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Automobili;
    private javax.swing.JLabel Klijenti;
    private javax.swing.JLabel Pocetna;
    private javax.swing.JLabel Racuni;
    private javax.swing.JPanel SideMenu;
    private javax.swing.JLabel Ugovori;
    // End of variables declaration//GEN-END:variables
}
