/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insertPages;

/**
 *
 * @author Administrator
 */

import db.DBConnection;
import java.sql.*;
import mainPages.ContractsPage;

public class FinalizeContractPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinalizeContractPage.class.getName());
    private int IdUgovora;

    /**
     * Creates new form FinalizeContract
     * @param IdUgovora
     */
    public FinalizeContractPage(int IdUgovora) {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        this.IdUgovora = IdUgovora;
        
        setPanelEnabled(panelOstecenje, false);
        osveziUkupnuCenu();
    }
    
    public FinalizeContractPage() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        setPanelEnabled(panelOstecenje, false);
    }

    private void setPanelEnabled(java.awt.Container panel, boolean isEnabled) {
        java.awt.Component[] components = panel.getComponents();
        for (java.awt.Component component : components) {
            component.setEnabled(isEnabled);
        }
        panel.setEnabled(isEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelOstecenje = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OpisOstecenja = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TroskoviOstecenja = new javax.swing.JTextField();
        unesiOstecenje = new javax.swing.JButton();
        finalizujBtn = new javax.swing.JButton();
        chckOstecenje = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        racun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RENT A CAR");

        jButton1.setText("<- Nazad");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        OpisOstecenja.setColumns(20);
        OpisOstecenja.setRows(5);
        jScrollPane1.setViewportView(OpisOstecenja);

        jLabel1.setText("Opis ostecenja");

        jLabel2.setText("Troskovi ostecenja");

        TroskoviOstecenja.addActionListener(this::TroskoviOstecenjaActionPerformed);

        unesiOstecenje.setText("Unesi");
        unesiOstecenje.addActionListener(this::unesiOstecenjeActionPerformed);

        javax.swing.GroupLayout panelOstecenjeLayout = new javax.swing.GroupLayout(panelOstecenje);
        panelOstecenje.setLayout(panelOstecenjeLayout);
        panelOstecenjeLayout.setHorizontalGroup(
            panelOstecenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOstecenjeLayout.createSequentialGroup()
                .addGroup(panelOstecenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOstecenjeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOstecenjeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOstecenjeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOstecenjeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TroskoviOstecenja, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOstecenjeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(unesiOstecenje, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        panelOstecenjeLayout.setVerticalGroup(
            panelOstecenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOstecenjeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TroskoviOstecenja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(unesiOstecenje)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        finalizujBtn.setText("Finalizuj i generisi racun");
        finalizujBtn.addActionListener(this::finalizujBtnActionPerformed);

        chckOstecenje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chckOstecenje.setText("Postoje li ostecenja?");
        chckOstecenje.addActionListener(this::chckOstecenjeActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Finalni racun");

        racun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        racun.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 168, Short.MAX_VALUE)
                .addComponent(panelOstecenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(chckOstecenje, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(finalizujBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(racun, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chckOstecenje)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOstecenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(racun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(finalizujBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TroskoviOstecenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TroskoviOstecenjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TroskoviOstecenjaActionPerformed

    private void unesiOstecenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unesiOstecenjeActionPerformed
        // TODO add your handling code here:
        String opis = OpisOstecenja.getText();
        String trosakStr = TroskoviOstecenja.getText();

        if (opis.isEmpty() || trosakStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Popunite sva polja za oštećenje!");
            return;
        }

        try (Connection con = DBConnection.getConnection()) {
        // 1. Isključi auto-commit da bismo kontrolisali transakciju
            con.setAutoCommit(false);

            int trosak = Integer.parseInt(trosakStr);

            // 2. INSERT u tabelu Ostecenja
            String sqlOstecenje = "INSERT INTO Ostecenja (BrojUgovora, OpisOstecenja, TroskoviPopravke) VALUES (?, ?, ?)";
            try (PreparedStatement ps1 = con.prepareStatement(sqlOstecenje)) {
                ps1.setInt(1, this.IdUgovora);
                ps1.setString(2, opis);
                ps1.setDouble(3, trosak);
                ps1.executeUpdate();
            }

            // 3. UPDATE TroskoviNajma u tabeli Ugovori
            // Sabiramo postojeću vrednost sa novim troškom oštećenja
            String sqlUpdateUgovor = "UPDATE Ugovori SET TroskoviNajma = TroskoviNajma + ? WHERE BrojUgovora = ?";
            try (PreparedStatement ps2 = con.prepareStatement(sqlUpdateUgovor)) {
                ps2.setDouble(1, trosak);
                ps2.setInt(2, this.IdUgovora);
                ps2.executeUpdate();
            }

            // 4. Potvrdi promene u bazi
            con.commit();

            // 5. Ažuriraj prikaz na labeli UkupnaCena (moraš prethodno dohvatiti novu vrednost iz baze)
            osveziUkupnuCenu();

            javax.swing.JOptionPane.showMessageDialog(this, "Oštećenje evidentirano i troškovi ažurirani!");
            unesiOstecenje.setEnabled(false); // Ovo već imaš
            chckOstecenje.setSelected(false); // Uklanja "check" sa checkbox-a
            TroskoviOstecenja.setText("");
            OpisOstecenja.setText("");
            setPanelEnabled(panelOstecenje, false);
            // Spreči dupli unos

        } catch (SQLException | NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + ex.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Greška pri evidentiranju štete", ex);
        }
    }//GEN-LAST:event_unesiOstecenjeActionPerformed

    private void osveziUkupnuCenu() {
        // 1. Konekciju otvaramo unutar try-with-resources da bi se automatski zatvorila
        String sql = "SELECT TroskoviNajma FROM Ugovori WHERE BrojUgovora = ?";

        try (Connection con = DBConnection.getConnection(); 
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, this.IdUgovora);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int novaCena = rs.getInt("TroskoviNajma");
                    // Postavi vrednost na tvoju labelu (proveri da li se zove racun ili UkupnaCena)
                    racun.setText(novaCena + " €");
                }
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Greška pri osvežavanju cene", ex);
            // Opciono: javax.swing.JOptionPane.showMessageDialog(this, "Greška pri čitanju cene!");
        }
    }
    
    private void chckOstecenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckOstecenjeActionPerformed
        // TODO add your handling code here:
        boolean isChecked = chckOstecenje.isSelected();
    
    // Ako je čekirano, omogućavamo polja, inače ih gasimo
        setPanelEnabled(panelOstecenje, isChecked);

        // Opciono: Očisti polja ako korisnik odčekira checkbox
        if (!isChecked) {
            OpisOstecenja.setText("");
            TroskoviOstecenja.setText("");
            unesiOstecenje.setEnabled(false);
        }
    }//GEN-LAST:event_chckOstecenjeActionPerformed

    private void finalizujBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizujBtnActionPerformed
        // TODO add your handling code here:
     try (Connection con = DBConnection.getConnection()) {
        // Isključujemo auto-commit radi sigurnosti transakcije
        con.setAutoCommit(false);

        // 1. Dobijamo trenutnu cenu i AutomobilID iz ugovora
        String sqlSelect = "SELECT TroskoviNajma, AutomobilID FROM Ugovori WHERE BrojUgovora = ?";
        PreparedStatement psSelect = con.prepareStatement(sqlSelect);
        psSelect.setInt(1, this.IdUgovora);
        ResultSet rs = psSelect.executeQuery();

        double trenutnaCena = 0;
        int automobilID = -1;
        if (rs.next()) {
            trenutnaCena = rs.getDouble("TroskoviNajma");
            automobilID = rs.getInt("AutomobilID");
        }

        // 2. Kalkulacija finalne cene
        double trosakOstecenja = 0;
        if (chckOstecenje.isSelected()) {
            try {
                trosakOstecenja = Double.parseDouble(TroskoviOstecenja.getText());
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Unesite validan broj za troškove oštećenja!");
                return;
            }
        }
        double finalnaCena = trenutnaCena + trosakOstecenja;

        // 3. UPDATE ugovora (zatvaranje i finalna cena)
        String sqlUpdate = "UPDATE Ugovori SET TroskoviNajma = ?, Status = 'Zatvoren' WHERE BrojUgovora = ?";
        PreparedStatement psUpdate = con.prepareStatement(sqlUpdate);
        psUpdate.setDouble(1, finalnaCena);
        psUpdate.setInt(2, this.IdUgovora);
        psUpdate.executeUpdate();

        // 4. UPDATE statusa automobila koristeći AutomobilID
        if (automobilID != -1) {
            String sqlAuto = "UPDATE Automobili SET Status = 'Slobodan' WHERE Id = ?"; // Pretpostavljam da je ključ u Automobili tabeli 'Id'
            PreparedStatement psAuto = con.prepareStatement(sqlAuto);
            psAuto.setInt(1, automobilID);
            psAuto.executeUpdate();
        }

        // 5. INSERT u tabelu Racuni
        String sqlRacun = "INSERT INTO Racuni (BrojUgovora, DatumIzdavanja, UkupanIznos) VALUES (?, ?, ?)";
        PreparedStatement psRacun = con.prepareStatement(sqlRacun);
        psRacun.setInt(1, this.IdUgovora);
        psRacun.setDate(2, new java.sql.Date(System.currentTimeMillis()));
        psRacun.setDouble(3, finalnaCena);
        psRacun.executeUpdate();

        // Potvrđujemo sve promene
        con.commit();

        javax.swing.JOptionPane.showMessageDialog(this, "Ugovor finalizovan! Automobil je sada slobodan.");
        
        mainPages.ContractsPage contracts = new mainPages.ContractsPage();
        contracts.setVisible(true);
        this.dispose();

    } catch (SQLException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Greška pri finalizaciji ugovora", ex);
        javax.swing.JOptionPane.showMessageDialog(this, "Došlo je do greške u bazi podataka!");
    }
    }//GEN-LAST:event_finalizujBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ContractsPage contracts = new ContractsPage();
        contracts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinalizeContractPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OpisOstecenja;
    private javax.swing.JTextField TroskoviOstecenja;
    private javax.swing.JCheckBox chckOstecenje;
    private javax.swing.JButton finalizujBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelOstecenje;
    private javax.swing.JLabel racun;
    private javax.swing.JButton unesiOstecenje;
    // End of variables declaration//GEN-END:variables
}
