/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insertPages;

import java.awt.HeadlessException;
import java.sql.SQLException;
import mainPages.ContractsPage;
import mainPages.HomePage;
import session.SelectedCar;
import session.Session;

/**
 *
 * @author Administrator
 */
public class MakeAContract extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MakeAContract.class.getName());
    private java.util.List<Integer> klijentIds = new java.util.ArrayList<>();

    /**
     * Creates new form MakeAContract
     */
    public MakeAContract() {
        initComponents();
        loadClients();
        jButton2.setEnabled(false); // Onemogući na početku
        ukupnaCenaTxt.setText("0.00");

        // Dodaj listener za datum
        datumVracanja.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { proveriIzracunaj(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { proveriIzracunaj(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { proveriIzracunaj(); }
        });

        // Dodaj listener za ComboBox
        klijentComboBox.addActionListener(e -> proveriIzracunaj());

        modelTxt.setText(SelectedCar.Model);
        kategorijaTxt.setText(SelectedCar.Kategorija);
        godisteTxt.setText(String.valueOf(SelectedCar.Godiste));
        cenaTxt.setText(String.valueOf(SelectedCar.CenaPoDanu));
        kilometrazaTxt.setText(String.valueOf(SelectedCar.Kilometraza));
        bojaTxt.setText(SelectedCar.Boja);
        registracijaTxt.setText(SelectedCar.Registracija);
    
    }
    
    private void proveriIzracunaj() {
        String datumStr = datumVracanja.getText();
        if (datumStr.isEmpty() || klijentComboBox.getSelectedIndex() == -1) {
            jButton2.setEnabled(false);
            return;
        }

        try {
            java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("M/d/yy");
            java.time.LocalDate danas = java.time.LocalDate.now();
            java.time.LocalDate vracanje = java.time.LocalDate.parse(datumStr, dtf);

            if (vracanje.isAfter(danas)) {
                long brojDana = java.time.temporal.ChronoUnit.DAYS.between(danas, vracanje);
                double cenaPoDanu = Double.parseDouble(cenaTxt.getText());
                double ukupna = brojDana * cenaPoDanu;

                ukupnaCenaTxt.setText(String.format("%.2f", ukupna));
                jButton2.setEnabled(true);
            } else {
                jButton2.setEnabled(false);
            }
        } catch (Exception e) {
            jButton2.setEnabled(false); // Ako format datuma nije dobar
        }
    }

    private void loadClients() {
        // 1. Postavi prazan model - ovo sigurno briše sve prethodne stavke
        klijentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        klijentIds.clear(); 

        String query = "SELECT Id, ime, prezime FROM klijenti"; 

        try (java.sql.Connection conn = db.DBConnection.getConnection();
             java.sql.PreparedStatement pst = conn.prepareStatement(query);
             java.sql.ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                String klijent = rs.getString("ime") + " " + rs.getString("prezime");
                // 2. Dodaj stavku
                klijentComboBox.addItem(klijent);
                klijentIds.add(rs.getInt("Id"));
            }

            // Opcionalno: proveri da li je lista prazna
            if (klijentIds.isEmpty()) {
                System.out.println("Upozorenje: Nema klijenata u bazi!");
            }

        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Greška pri učitavanju klijenata", e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        datumVracanja = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        klijentComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modelTxt = new javax.swing.JLabel();
        kategorijaTxt = new javax.swing.JLabel();
        godisteTxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cenaTxt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kilometrazaTxt = new javax.swing.JLabel();
        bojaTxt = new javax.swing.JLabel();
        registracijaTxt = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ukupnaCenaTxt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RENT A CAR");

        jButton1.setText("<- Nazad");

        datumVracanja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel1.setText("Planirani datum vracanja");

        jLabel2.setText("Nacin placanja");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kes", "Kartica", "Cek" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel3.setText("Klijent:");

        klijentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setText("Podaci o automobilu za iznajmljivanje");

        jLabel6.setText("Model :");

        jLabel7.setText("Kategorija :");

        jLabel8.setText("Godiste :");

        modelTxt.setText("model");

        kategorijaTxt.setText("kategorija");

        godisteTxt.setText("2000");

        jLabel9.setText("Cena po danu :");

        cenaTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cenaTxt.setText("cena");

        jLabel11.setText("€");

        jLabel10.setText("Kilometraza :");

        jLabel12.setText("Boja :");

        jLabel13.setText("Registracija :");

        kilometrazaTxt.setText("km");

        bojaTxt.setText("b");

        registracijaTxt.setText("tt-04");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cenaTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(bojaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kategorijaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(godisteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(kilometrazaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(registracijaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kategorijaTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(godisteTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cenaTxt)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kilometrazaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bojaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(registracijaTxt))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jButton2.setText("Napravi ugovor");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Ukupna cena:");

        ukupnaCenaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ukupnaCenaTxt.setText("jLabel15");

        jLabel15.setText("Format: M/D/YY (npr. 6/27/26)");

        jLabel16.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox1, 0, 126, Short.MAX_VALUE)
                                        .addComponent(klijentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ukupnaCenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)))))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(klijentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ukupnaCenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = klijentComboBox.getSelectedIndex();
        if (selectedIndex == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Molimo izaberite klijenta.");
            return;
        }

        try {
            // 1. Parsiranje datuma iz tvog formata (M/d/yy)
            // DateTimeFormatter.ofPattern("M/d/yy") odgovara tvom formatu 6/26/26
            java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("M/d/yy");

            java.time.LocalDate danas = java.time.LocalDate.now();
            java.time.LocalDate vracanje = java.time.LocalDate.parse(datumVracanja.getText(), dtf);

            // 2. Kalkulacija broja dana i cene
            long brojDana = java.time.temporal.ChronoUnit.DAYS.between(danas, vracanje);
            if (brojDana <= 0) brojDana = 1; // Ako je isti dan ili greska, racunamo minimum 1 dan

            double cenaPoDanu = Double.parseDouble(cenaTxt.getText());
            double ukupnaCena = brojDana * cenaPoDanu;

            // 3. SQL Upiti
            String insertUgovor = "INSERT INTO ugovori (DatumSklapanja, PlaniraniDatumVracanja, TroskoviNajma, NacinPlacanja, Status, AutomobilID, KlijentID,SluzbenikID) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            String updateAuto = "UPDATE automobili SET Status = 'Izdat' WHERE Id = ?";

            try (java.sql.Connection conn = db.DBConnection.getConnection()) {
                conn.setAutoCommit(false); // Transakcija

                // Insert ugovora
                try (java.sql.PreparedStatement pstUgovor = conn.prepareStatement(insertUgovor)) {
                    pstUgovor.setDate(1, java.sql.Date.valueOf(danas));
                    pstUgovor.setDate(2, java.sql.Date.valueOf(vracanje)); // Sada ce biti ispravno 2026-06-28
                    pstUgovor.setDouble(3, ukupnaCena);
                    pstUgovor.setString(4, jComboBox1.getSelectedItem().toString());
                    pstUgovor.setString(5, "Aktivan");
                    pstUgovor.setInt(6, SelectedCar.Id);
                    pstUgovor.setInt(7, klijentIds.get(selectedIndex));
                    pstUgovor.setInt(8,Session.id);
                    pstUgovor.executeUpdate();
                }

                // Update statusa automobila
                try (java.sql.PreparedStatement pstAuto = conn.prepareStatement(updateAuto)) {
                    pstAuto.setInt(1, SelectedCar.Id);
                    pstAuto.executeUpdate();
                }

                conn.commit();
                javax.swing.JOptionPane.showMessageDialog(this, "Ugovor kreiran! Ukupna cena za " + brojDana + " dana je: " + ukupnaCena);
                
                ContractsPage contracts = new ContractsPage();
                contracts.setVisible(true);

                this.dispose(); 
            }
        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pogrešan format datuma! Unesite format kao na primeru: 6/26/26");
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MakeAContract().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bojaTxt;
    private javax.swing.JLabel cenaTxt;
    private javax.swing.JFormattedTextField datumVracanja;
    private javax.swing.JLabel godisteTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kategorijaTxt;
    private javax.swing.JLabel kilometrazaTxt;
    private javax.swing.JComboBox<String> klijentComboBox;
    private javax.swing.JLabel modelTxt;
    private javax.swing.JLabel registracijaTxt;
    private javax.swing.JLabel ukupnaCenaTxt;
    // End of variables declaration//GEN-END:variables
}
